### ISSUE TITLE
[Bug] Uncaught (in promise) DOMException: Failed to execute 'open' on 'XMLHttpRequest

### ISSUE THREAD

**Issue by Aju100** [LiquidGalaxyLAB/Presentation-Tool#20]
Hello opensource enthusiast,

I have been gone through the README file and install all the required dependencies for the backend and frontend. I get a few errors in the frontend ie. console. Can you please explain what it is ?? Is it a cors issue?
![error](https://user-images.githubusercontent.com/29862610/110346970-1d2d8f80-8056-11eb-88fe-10291711b0cd.png)

Looking forward to a positive response on it.

**Comment by KarinePistili** [comment]
I think it is not being capable of getting the data from the database. As soon as it opens the homepage there is a request to get all presentations stored in mongo. So a few things for you to investigate:

- is the backend returning data? (try using postman, the api-docs swagger, curl, etc)
- are all .env files well configured?
- do you have a functional installation of mongo?
- did you open the tcp ports and reboot the computer later?
- do you have a liquid galaxy installation?

try to verify those, and if you still can find the problem, we can think a little bit more on what could it be

**Comment by Aju100** [comment]
Hi, @KarinePistili ,

Yes I have the following things
- Backend returns the JSON format data
- Installed MongoDB
- Yes TCP ports are open and the computer is also restarted
- As my machine, OS is installed on EFI Boot loader so I am not able to install a Virtual machine, but I had installed Liquid Galaxy on my machine instead of a virtual one.
- configure .env file too

content of .env
```bash
    VUE_APP_LG_IP=ip_of_my_machine_as_I_had_installed_on_my_machine
    VUE_APP_LG_PORT=127.0.0.1:3000
```

I wanted to know my env properly configure or not, or there are other problems?

I am looking positive message on this issue as I may not successfully create any new presentation. Thank you


Regards,
Aju Tamang

**Comment by KarinePistili** [comment]
Oh I see now @Aju100 , the problem is on the .env. In the PORT var you need to put only the port you are using, then in your case it will be only 3000. It should look like this for example:

    VUE_APP_LG_IP=192.168.0.112
    VUE_APP_LG_PORT=3000

What was happening is that the frontend was trying to make a request with https://localhost:127.0.0.1:3000, so that is a invalid url and that's why it wasn't working
