### ISSUE TITLE
Dockerize the backend nodejs api server

### ISSUE THREAD

**Issue by Aju100** [LiquidGalaxyLAB/Presentation-Tool#21]
Hi, @KarinePistili ,

As Presentation-Tool runs backend on node js. It's always better to run codebase on the container 
so that other developers won't have any issue with installing dependencies and software version 
incompatibility. 

Docker is the solution for it as it provides many solutions like compatibility, shine for microservice
architecture, portability.

Regards,
Aju

**Comment by KarinePistili** [comment]
Hi @Aju100 , I agree with you and I think this would benefit greatly the project. Feel free to work on it and make a pull request when done.

**Comment by Aju100** [comment]
@KarinePistili  Thank you for your response and it would make better enhancement for the backend of the codebase. I have opened up the PR #23 for it. Feedbacks are appreciated
