### ISSUE TITLE
Aspect ratio of multimedia

### ISSUE THREAD

**Issue by mlmosteiro** [LiquidGalaxyLAB/Presentation-Tool#4]
The video and audio multimedia has a different aspect ratio than the original: here a good example of the correct behaviour

![image](https://user-images.githubusercontent.com/15185584/88951758-b6155480-d296-11ea-9cee-c417ba521961.png)

**Comment by KarinePistili** [comment]
![WhatsApp Image 2020-08-04 at 19 02 22 (1)](https://user-images.githubusercontent.com/43211581/89351512-8dbb9a80-d688-11ea-8db3-e62edce0ff23.jpeg)
![WhatsApp Image 2020-08-04 at 19 02 21 (1)](https://user-images.githubusercontent.com/43211581/89351513-8eecc780-d688-11ea-9f96-ab1ed22342a1.jpeg)
![WhatsApp Image 2020-08-04 at 19 02 21](https://user-images.githubusercontent.com/43211581/89351516-8f855e00-d688-11ea-975a-560e6fe85f65.jpeg)

Final results after changes
